<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>AskARabbi.CorpusPublisher</AssemblyName>
    <RootNamespace>AskARabbi.CorpusPublisher</RootNamespace>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Library\AskARabbiLIB\AskARabbiLIB.csproj" />
  </ItemGroup>

</Project>
