#!/usr/bin/env python3
"""Create an AI-facing JSON catalog for the normalized Sefaria documents."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import tempfile
import urllib.parse
from pathlib import Path
from typing import Any, Iterable


SchemaVersion = "1.3"
PermissiveLicenseStatus = "permissive"
PermissiveLicensePatterns = (
    re.compile(r"public domain"),
    re.compile(r"pd"),
    re.compile(r"cc0(?:[ -]\d+(?:\.\d+)*)?"),
    re.compile(r"cc(?:-| )by(?:[ -]\d+(?:\.\d+)*)?"),
    re.compile(r"cc(?:-| )by(?:-| )sa(?:[ -]\d+(?:\.\d+)*)?"),
)
DeniedVersionTitles = frozenset({
    "Miqra Mevoar, trans. and edited by David Kokhav, Jerusalem 2020",
})
DeniedVersionTitleKeys = frozenset(title.casefold() for title in DeniedVersionTitles)
LanguageNames = {
    "ar": "Arabic",
    "ca": "Catalan",
    "de": "German",
    "en": "English",
    "eo": "Esperanto",
    "es": "Spanish",
    "fa": "Persian",
    "fi": "Finnish",
    "fr": "French",
    "he": "Hebrew",
    "hu": "Hungarian",
    "it": "Italian",
    "itk": "Judeo-Italian",
    "lad": "Ladino",
    "pl": "Polish",
    "pt": "Portuguese",
    "ru": "Russian",
    "yi": "Yiddish",
}
CollectionOrder = {
    "Torah": 0,
    "Tanakh": 1,
    "Mishnah": 2,
    "Talmud": 3,
    "Halakhah": 4,
    "Kabbalah": 5,
    "Musar": 6,
}


def parseArguments() -> argparse.Namespace:
    """Parse command-line arguments for the document-manifest generator."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", type=Path, default=Path("Data"), help="Project data directory (default: Data).")
    parser.add_argument("--output", type=Path, help="Output JSON path (default: Data/NormalizedData/Sefaria/Metadata/document-manifest.json).")
    return parser.parse_args()


def readJsonLines(path: Path) -> list[dict[str, Any]]:
    """Read a UTF-8 JSON Lines file and report the precise location of invalid records."""
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as stream:
        for lineNumber, line in enumerate(stream, start=1):
            if not line.strip():
                continue
            try:
                value = json.loads(line)
            except json.JSONDecodeError as exception:
                raise ValueError(f"Invalid JSON in {path} at line {lineNumber}: {exception}") from exception
            if not isinstance(value, dict):
                raise ValueError(f"Expected an object in {path} at line {lineNumber}.")
            records.append(value)
    return records


def writeBytesAtomically(path: Path, content: bytes) -> None:
    """Write generated bytes atomically so interrupted work never appears complete."""
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporaryName = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".part", dir=path.parent)
    temporaryPath = Path(temporaryName)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        temporaryPath.replace(path)
    except BaseException:
        temporaryPath.unlink(missing_ok=True)
        raise


def writeJson(path: Path, value: Any) -> None:
    """Write readable, deterministic UTF-8 JSON with a trailing newline."""
    content = (json.dumps(value, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    writeBytesAtomically(path, content)


def sha256File(path: Path) -> str:
    """Calculate the SHA-256 checksum of a file without loading it entirely into memory."""
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while chunk := stream.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def requireString(record: dict[str, Any], fieldName: str, sourceName: str) -> str:
    """Return a required nonempty string field or raise a contextual validation error."""
    value = record.get(fieldName)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"Record from {sourceName} is missing required field '{fieldName}'.")
    return value.strip()


def optionalString(record: dict[str, Any], fieldName: str) -> str | None:
    """Return an optional nonempty string field as a stripped value."""
    value = record.get(fieldName)
    if not isinstance(value, str):
        return None
    normalizedValue = value.strip()
    return normalizedValue or None


def isPermissiveLicense(versionTitle: str, licenseName: str | None) -> bool:
    """Return whether a version has an explicitly permissive license."""
    if versionTitle.casefold() == "merged" or versionTitle.casefold() in DeniedVersionTitleKeys:
        return False
    normalizedLicense = (licenseName or "").strip().casefold()
    if "-nc" in normalizedLicense or "noncommercial" in normalizedLicense or "non-commercial" in normalizedLicense:
        return False
    return any(pattern.fullmatch(normalizedLicense) for pattern in PermissiveLicensePatterns)


def licenseCategory(licenseName: str) -> str:
    """Map an exact permissive license label to the manifest's stable license enum value."""
    normalizedLicense = licenseName.strip().casefold()
    if re.fullmatch(r"(?:public domain|pd)", normalizedLicense):
        return "publicDomain"
    if re.fullmatch(r"cc0(?:[ -]\d+(?:\.\d+)*)?", normalizedLicense):
        return "cc0"
    if re.fullmatch(r"cc(?:-| )by(?:-| )sa(?:[ -]\d+(?:\.\d+)*)?", normalizedLicense):
        return "ccBySa"
    if re.fullmatch(r"cc(?:-| )by(?:[ -]\d+(?:\.\d+)*)?", normalizedLicense):
        return "ccBy"
    raise ValueError(f"Unsupported permissive license label: {licenseName!r}")


def isAbsoluteHttpUrl(value: str | None) -> bool:
    """Return whether a value is an absolute HTTP or HTTPS URL."""
    if not value:
        return False
    parsed = urllib.parse.urlparse(value)
    return parsed.scheme.casefold() in {"http", "https"} and bool(parsed.netloc)


def repositoryRelativePath(path: Path, repositoryRoot: Path) -> str:
    """Return a portable repository-relative path and reject paths outside the repository."""
    resolvedPath = path.resolve()
    try:
        return resolvedPath.relative_to(repositoryRoot).as_posix()
    except ValueError as exception:
        raise ValueError(f"Manifest path is outside the repository: {resolvedPath}") from exception


def resolveDataPath(dataRoot: Path, relativeValue: str, fieldName: str) -> Path:
    """Resolve a data-relative manifest path while preventing traversal outside Data."""
    resolvedPath = (dataRoot / Path(relativeValue)).resolve()
    try:
        resolvedPath.relative_to(dataRoot)
    except ValueError as exception:
        raise ValueError(f"Field '{fieldName}' points outside the data root: {relativeValue}") from exception
    return resolvedPath


def getLanguageName(languageCode: str, rawRecord: dict[str, Any]) -> str:
    """Map a Sefaria language code to a human-readable name with a metadata fallback."""
    mappedName = LanguageNames.get(languageCode.casefold())
    if mappedName:
        return mappedName
    familyName = optionalString(rawRecord, "languageFamilyName")
    return familyName.title() if familyName else f"Unknown ({languageCode})"


def getCategoryDetails(rawRecord: dict[str, Any]) -> list[str]:
    """Return the ordered Sefaria category path after validating its shape."""
    categories = rawRecord.get("categories")
    if not isinstance(categories, list) or not all(isinstance(category, str) and category.strip() for category in categories):
        raise ValueError(f"Raw record for {rawRecord.get('title', '<unknown>')} has invalid categories.")
    return [category.strip() for category in categories]


def getGenreDescription(title: str, collection: str, categories: list[str]) -> tuple[str, str]:
    """Describe a document's Sefaria genre and the addressing structure used in its references."""
    if collection == "Torah":
        return f"{title} is a book of the Torah", "chapter-and-verse"
    if collection == "Tanakh":
        division = categories[1] if len(categories) > 1 else "Tanakh"
        return f"{title} is a book in the {division} section of the Tanakh", "chapter-and-verse"
    if collection == "Mishnah":
        order = categories[1] if len(categories) > 1 else None
        suffix = f" in {order}" if order else ""
        return f"{title} is a Mishnah tractate{suffix}", "chapter-and-mishnah"
    if collection == "Talmud":
        tradition = categories[1] if len(categories) > 1 else None
        division = categories[2] if len(categories) > 2 else None
        if division == "Minor Tractates":
            return f"{title} is a Minor Tractate associated with the Babylonian Talmud", "citation-addressable"
        talmudName = "Babylonian Talmud" if tradition == "Bavli" else "Jerusalem Talmud" if tradition == "Yerushalmi" else "Talmud"
        suffix = f" in {division}" if division else ""
        return f"{title} is a {talmudName} tractate{suffix}", "citation-addressable"
    return f"{title} is a Sefaria document in the {collection} collection", "citation-addressable"


def createDescription(title: str, collection: str, categories: list[str], languageName: str, firstReference: str | None, lastReference: str | None) -> str:
    """Create a factual one- or two-sentence description from source metadata."""
    genreDescription, referenceStructure = getGenreDescription(title, collection, categories)
    description = f"{genreDescription}, provided by Sefaria in {languageName}."
    if firstReference and lastReference and firstReference == lastReference:
        return f"{description} Its normalized text contains the {referenceStructure} segment {firstReference}."
    if firstReference and lastReference:
        return f"{description} Its normalized {referenceStructure} segments span from {firstReference} through {lastReference}."
    return description


def createRawIndex(records: Iterable[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Index raw text metadata by its data-root-relative file path."""
    index: dict[str, dict[str, Any]] = {}
    for record in records:
        if record.get("artifactType") != "text":
            continue
        versionTitle = str(record.get("versionTitle") or "")
        licenseName = optionalString(record, "license")
        if record.get("licenseStatus") != PermissiveLicenseStatus or not isPermissiveLicense(versionTitle, licenseName):
            raise ValueError(f"Raw manifest contains a non-permissive text record: {record.get('localPath', '<unknown>')}")
        localPath = requireString(record, "localPath", "raw manifest")
        if localPath in index:
            raise ValueError(f"Raw manifest contains duplicate localPath '{localPath}'.")
        index[localPath] = record
    return index


def validateJoinedMetadata(normalizedRecord: dict[str, Any], rawRecord: dict[str, Any], rawRelativePath: str) -> None:
    """Ensure a normalized record agrees with the raw Sefaria metadata it references."""
    for fieldName in ("title", "collection", "actualLanguage", "versionTitle", "licenseStatus"):
        if normalizedRecord.get(fieldName) != rawRecord.get(fieldName):
            raise ValueError(f"Field '{fieldName}' disagrees between normalized and raw metadata for {rawRelativePath}.")
    normalizedRawChecksum = requireString(normalizedRecord, "rawSha256", "normalized manifest")
    rawManifestChecksum = requireString(rawRecord, "sha256", "raw manifest")
    if normalizedRawChecksum != rawManifestChecksum:
        raise ValueError(f"Raw checksum disagrees between normalized and raw metadata for {rawRelativePath}.")
    for fieldName in ("workKey", "usageNote"):
        if normalizedRecord.get(fieldName) != rawRecord.get(fieldName):
            raise ValueError(f"Field '{fieldName}' disagrees between normalized and raw metadata for {rawRelativePath}.")


def createDocumentEntry(normalizedRecord: dict[str, Any], rawRecord: dict[str, Any], dataRoot: Path, repositoryRoot: Path) -> dict[str, Any]:
    """Create one validated AI-facing document catalog entry."""
    if normalizedRecord.get("licenseStatus") != PermissiveLicenseStatus or rawRecord.get("licenseStatus") != PermissiveLicenseStatus:
        raise ValueError(f"Refusing to catalog a non-permissive document: {normalizedRecord.get('normalizedPath', '<unknown>')}")
    normalizedRelativePath = requireString(normalizedRecord, "normalizedPath", "normalized manifest")
    rawRelativePath = requireString(normalizedRecord, "rawPath", "normalized manifest")
    validateJoinedMetadata(normalizedRecord, rawRecord, rawRelativePath)
    normalizedPath = resolveDataPath(dataRoot, normalizedRelativePath, "normalizedPath")
    rawPath = resolveDataPath(dataRoot, rawRelativePath, "rawPath")
    if not normalizedPath.is_file():
        raise FileNotFoundError(f"Normalized document does not exist: {normalizedPath}")
    if not rawPath.is_file():
        raise FileNotFoundError(f"Raw source does not exist: {rawPath}")

    expectedChecksum = requireString(normalizedRecord, "normalizedSha256", "normalized manifest")
    actualChecksum = sha256File(normalizedPath)
    if actualChecksum != expectedChecksum:
        raise ValueError(f"Normalized checksum mismatch for {normalizedPath}: expected {expectedChecksum}, found {actualChecksum}.")

    title = requireString(normalizedRecord, "title", "normalized manifest")
    collection = requireString(normalizedRecord, "collection", "normalized manifest")
    languageCode = requireString(normalizedRecord, "actualLanguage", "normalized manifest")
    languageName = getLanguageName(languageCode, rawRecord)
    categories = getCategoryDetails(rawRecord)
    firstReference = optionalString(normalizedRecord, "firstReference")
    lastReference = optionalString(normalizedRecord, "lastReference")
    segmentCount = normalizedRecord.get("segmentCount")
    if not isinstance(segmentCount, int) or segmentCount < 0:
        raise ValueError(f"Normalized record for {normalizedRelativePath} has an invalid segmentCount.")

    rawChecksum = requireString(normalizedRecord, "rawSha256", "normalized manifest").lower()
    licenseName = requireString(normalizedRecord, "license", "normalized manifest")
    category = licenseCategory(licenseName)
    sourceUrl = requireString(rawRecord, "sourceUrl", "raw manifest")
    versionSource = optionalString(rawRecord, "versionSource")
    attributionUrl = versionSource if isAbsoluteHttpUrl(versionSource) else sourceUrl
    usageNote = optionalString(rawRecord, "usageNote")
    entry = {
        "documentId": f"sefaria:{rawChecksum}",
        "filePath": repositoryRelativePath(normalizedPath, repositoryRoot),
        "fileDescription": " ".join(part for part in (createDescription(title, collection, categories, languageName, firstReference, lastReference), usageNote) if part),
        "fileLanguage": languageName,
        "fileTitle": title,
        "fileLanguageCode": languageCode,
        "collection": collection,
        "categories": categories,
        "hebrewTitle": optionalString(rawRecord, "heTitle"),
        "versionTitle": optionalString(normalizedRecord, "versionTitle"),
        "versionSource": versionSource,
        "firstReference": firstReference,
        "lastReference": lastReference,
        "segmentCount": segmentCount,
        "license": licenseName,
        "licenseCategory": category,
        "requiresAttribution": category in {"ccBy", "ccBySa"},
        "requiresShareAlike": category == "ccBySa",
        "licenseStatus": PermissiveLicenseStatus,
        "sourceUrl": sourceUrl,
        "attributionUrl": attributionUrl,
        "rawFilePath": repositoryRelativePath(rawPath, repositoryRoot),
        "rawSha256": rawChecksum,
        "sha256": actualChecksum,
        "fileSizeBytes": normalizedPath.stat().st_size,
    }
    workKey = optionalString(rawRecord, "workKey")
    if workKey:
        entry["workKey"] = workKey
    if usageNote:
        entry["usageNote"] = usageNote
    return entry


def main() -> int:
    """Generate the complete, validated Sefaria document manifest."""
    arguments = parseArguments()
    repositoryRoot = Path(__file__).resolve().parent.parent
    dataRoot = arguments.data_root.resolve()
    rawManifestPath = dataRoot / "Raw" / "Sefaria" / "Metadata" / "manifest.jsonl"
    normalizedManifestPath = dataRoot / "NormalizedData" / "Sefaria" / "Metadata" / "manifest.jsonl"
    outputPath = arguments.output.resolve() if arguments.output else dataRoot / "NormalizedData" / "Sefaria" / "Metadata" / "document-manifest.json"

    if not rawManifestPath.is_file():
        raise FileNotFoundError(f"Raw Sefaria manifest does not exist: {rawManifestPath}")
    if not normalizedManifestPath.is_file():
        raise FileNotFoundError(f"Normalized Sefaria manifest does not exist: {normalizedManifestPath}")

    rawRecords = readJsonLines(rawManifestPath)
    normalizedRecords = readJsonLines(normalizedManifestPath)
    rawIndex = createRawIndex(rawRecords)
    documents: list[dict[str, Any]] = []
    for normalizedRecord in normalizedRecords:
        rawRelativePath = requireString(normalizedRecord, "rawPath", "normalized manifest")
        rawRecord = rawIndex.get(rawRelativePath)
        if rawRecord is None:
            raise ValueError(f"Normalized record refers to raw path absent from the raw manifest: {rawRelativePath}")
        documents.append(createDocumentEntry(normalizedRecord, rawRecord, dataRoot, repositoryRoot))

    documents.sort(
        key=lambda document: (
            CollectionOrder.get(str(document["collection"]), len(CollectionOrder)),
            str(document["fileTitle"]).casefold(),
            str(document["fileLanguage"]).casefold(),
            str(document.get("versionTitle") or "").casefold(),
            str(document["filePath"]).casefold(),
        )
    )
    filePaths = [str(document["filePath"]) for document in documents]
    if len(filePaths) != len(set(filePaths)):
        raise ValueError("Generated document manifest contains duplicate filePath values.")
    documentIds = [str(document["documentId"]) for document in documents]
    if len(documentIds) != len(set(documentIds)):
        raise ValueError("Generated document manifest contains duplicate documentId values.")

    generatedAtUtc = dt.datetime.now(dt.timezone.utc).isoformat().replace("+00:00", "Z")
    manifest = {
        "schemaVersion": SchemaVersion,
        "sourceProvider": "Sefaria",
        "generatedAtUtc": generatedAtUtc,
        "filePathBase": "repository root",
        "description": "AI-facing catalog of permissively licensed normalized Sefaria documents. Select candidate files by collection, title, language, description, and canonical reference range before reading their Markdown content.",
        "documentCount": len(documents),
        "sourceManifests": {
            "raw": repositoryRelativePath(rawManifestPath, repositoryRoot),
            "rawSha256": sha256File(rawManifestPath),
            "normalized": repositoryRelativePath(normalizedManifestPath, repositoryRoot),
            "normalizedSha256": sha256File(normalizedManifestPath),
        },
        "documents": documents,
    }
    writeJson(outputPath, manifest)
    print(f"Wrote {len(documents):,} document entries to {outputPath}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
