<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>AskARabbiPrototype</AssemblyName>
    <RootNamespace>AskARabbiPrototype</RootNamespace>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.56.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Library\AskARabbiLIB\AskARabbiLIB.csproj" />
  </ItemGroup>

</Project>
